---
function:
  handler: src/WT/netsuite_ap_wt.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ap-wt-${self:provider.stage}
  description: WT Netsuite AP api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/WT/netsuite_ap_wt.js
      - Helpers/**
  environment:
    # NETSUITE_INTERCOMPANY_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-netsuite-intercompany-state-machine-${self:provider.stage}
