service: omni-netsuite-services

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: true
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 30
  memorySize: 256
  deploymentBucket: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
  role: ${ssm:/omni-dw/${self:provider.stage}/lambda/role}
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  stackTags:
    Application: OmniNetsuite
    CreateBy: BizCloudExperts
    Version: "1.0"
    Environment: ${self:provider.stage}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    DBNAME: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    USER: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    HOST: ${ssm:/omni-dw/${self:provider.stage}/db/host~true}
    PASS: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    PORT: ${ssm:/omni-dw/${self:provider.stage}/db/port}
    db_username: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/name}
    db_host: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/omni-mcleod-finance/${self:provider.stage}/db/port}
    NETSUIT_AR_API_ENDPOINT: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/apiEndpoint}
    NETSUIT_AR_ACCOUNT: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/account}
    NETSUIT_AR_CONSUMER_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/consumerKey}
    NETSUIT_AR_CONSUMER_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/consumerSecret}
    NETSUIT_AR_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenKey}
    NETSUIT_AR_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenSecret}
    NETSUIT_CW_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenKeyCW}
    NETSUIT_CW_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenSecretCW}
    NETSUIT_M1_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenKeyM1}
    NETSUIT_M1_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenSecretM1}
    NETSUIT_TR_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenKeyTR}
    NETSUIT_TR_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/tokenSecretTR}

    NETSUIT_MCL_CONSUMER_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitMCL/authConfig/consumerKey}
    NETSUIT_MCL_CONSUMER_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitMCL/authConfig/consumerSecret}
    NETSUIT_MCL_TOKEN_KEY: ${ssm:/omni-dw/${self:provider.stage}/netsuitMCL/authConfig/tokenKeyMCL}
    NETSUIT_MCL_TOKEN_SECRET: ${ssm:/omni-dw/${self:provider.stage}/netsuitMCL/authConfig/tokenSecretMCL}

    NETSUIT_AR_WDSLPATH: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/authConfig/wdslPath}
    NETSUIT_AR_ERROR_TABLE: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/dynamo/errorTable}
    NETSUIT_AR_ERROR_EMAIL_HOST: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/host}
    NETSUIT_AR_ERROR_EMAIL_USER: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/user}
    NETSUIT_AR_ERROR_EMAIL_PASS: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/pass}
    NETSUIT_AR_ERROR_EMAIL_FROM: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/from}
    NETSUIT_AR_ERROR_EMAIL_TO: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/errorEmail/to}
    NETSUIT_AP_ERROR_EMAIL_TO: ${ssm:/omni-dw/${self:provider.stage}/netsuitAP/errorEmail/to}
    NETSUIT_AP_ERROR_TABLE: ${ssm:/omni-dw/${self:provider.stage}/netsuitAP/dynamo/errorTable}
    NETSUIT_AR_TR_ERROR_EMAIL_TO: ${ssm:/omni-dw/${self:provider.stage}/netsuitAR/TR/errorEmail/to}
    NETSUIT_AP_TR_ERROR_EMAIL_TO: ${ssm:/omni-dw/${self:provider.stage}/netsuitAP/TR/errorEmail/to}
    NETSUIT_INVOICE_REPORT: ${self:service}-invoice-report-${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-step-functions
  - serverless-pseudo-parameters

package:
  individually: true
  exclude:
    - "node_modules/**"
    - Jenkinsfile
    - "config/**"
    - "Helpers/**"
    - "src/**"
    - "*.*"

layers:
  commonNetsuiteLibs:
    path: lambdaLayer/lib
    compatibleRuntimes:
      - nodejs14.x

functions:
  netsuite-ar-wt: ${file(config/functions/WT/netsuite-ar-wt.yml):function}
  netsuite-customer-ar-wt: ${file(config/functions/WT/netsuite-customer-ar-wt.yml):function}
  netsuite-ap-wt: ${file(config/functions/WT/netsuite-ap-wt.yml):function}
  netsuite-vendor-ap-wt: ${file(config/functions/WT/netsuite-vendor-ap-wt.yml):function}

  netsuite-ar-wt-restlet: ${file(config/functions/WT_REST_API/netsuite-ar-wt.yml):function}
  netsuite-customer-ar-wt-restlet: ${file(config/functions/WT_REST_API/netsuite-customer-ar-wt.yml):function}
  netsuite-ap-wt-restlet: ${file(config/functions/WT_REST_API/netsuite-ap-wt.yml):function}
  netsuite-vendor-ap-wt-restlet: ${file(config/functions/WT_REST_API/netsuite-vendor-ap-wt.yml):function}

  netsuite-ar-cw-restlet: ${file(config/functions/CW_RESTLET_API/netsuite-ar-cw.yml):function}
  netsuite-customer-ar-cw-restlet: ${file(config/functions/CW_RESTLET_API/netsuite-customer-ar-cw.yml):function}
  netsuite-ap-cw-restlet: ${file(config/functions/CW_RESTLET_API/netsuite-ap-cw.yml):function}
  netsuite-vendor-ap-cw-restlet: ${file(config/functions/CW_RESTLET_API/netsuite-vendor-ap-cw.yml):function}

  netsuite-ar-cw: ${file(config/functions/CW/netsuite-ar-cw.yml):function}
  netsuite-customer-ar-cw: ${file(config/functions/CW/netsuite-customer-ar-cw.yml):function}
  netsuite-ap-cw: ${file(config/functions/CW/netsuite-ap-cw.yml):function}
  netsuite-vendor-ap-cw: ${file(config/functions/CW/netsuite-vendor-ap-cw.yml):function}

  netsuite-ar-m1: ${file(config/functions/M1/netsuite-ar-m1.yml):function}
  netsuite-customer-ar-m1: ${file(config/functions/M1/netsuite-customer-ar-m1.yml):function}
  netsuite-ap-m1: ${file(config/functions/M1/netsuite-ap-m1.yml):function}
  netsuite-vendor-ap-m1: ${file(config/functions/M1/netsuite-vendor-ap-m1.yml):function}

  netsuite-ar-tr: ${file(config/functions/TR/netsuite-ar-tr.yml):function}
  netsuite-customer-ar-tr: ${file(config/functions/TR/netsuite-customer-ar-tr.yml):function}
  netsuite-ap-tr: ${file(config/functions/TR/netsuite-ap-tr.yml):function}
  netsuite-vendor-ap-tr: ${file(config/functions/TR/netsuite-vendor-ap-tr.yml):function}

  netsuite-ar-mcl: ${file(config/functions/MC-LEOD/netsuite-ar-mcl.yml):function}
  netsuite-customer-ar-mcl: ${file(config/functions/MC-LEOD/netsuite-customer-ar-mcl.yml):function}
  # netsuite-ap-mcl: ${file(config/functions/MC-LEOD/netsuite-ap-mcl.yml):function}
  # netsuite-vendor-ap-mcl: ${file(config/functions/MC-LEOD/netsuite-vendor-ap-mcl.yml):function}

  #intar company fn
  netsuite-intercompany: ${file(config/functions/netsuite-intercompany.yml):function}
  netsuite-tr-intercompany: ${file(config/functions/netsuite-tr-intercompany.yml):function}
  netsuite-currency: ${file(config/functions/netsuite-currency.yml):function}

  #intra company fn
  intera-company-wt-mcl: ${file(config/functions/INTRA-COMPANY/intera-company-wt-mcl.yml):function}

  #report fn
  invoice-report: ${file(config/functions/invoice-report.yml):function}
  # mckesson-shipments-report: ${file(config/functions/mckesson-shipments-report.yml):function}

  netsuite-paid-invoices: ${file(config/functions/PAID-INVOICES/paid-invoices.yml):function}

stepFunctions:
  stateMachines:
    netsuite-ar-wt-state-machine: ${file(config/step-functions/WT/netsuite-ar-wt-state-machine.yml):stateMachine}
    netsuite-ap-wt-state-machine: ${file(config/step-functions/WT/netsuite-ap-wt-state-machine.yml):stateMachine}
    netsuite-customer-ar-wt-state-machine: ${file(config/step-functions/WT/netsuite-customer-ar-wt-state-machine.yml):stateMachine}
    netsuite-vendor-ap-wt-state-machine: ${file(config/step-functions/WT/netsuite-vendor-ap-wt-state-machine.yml):stateMachine}

    netsuite-ar-cw-state-machine: ${file(config/step-functions/CW/netsuite-ar-cw-state-machine.yml):stateMachine}
    netsuite-ap-cw-state-machine: ${file(config/step-functions/CW/netsuite-ap-cw-state-machine.yml):stateMachine}
    netsuite-customer-ar-cw-state-machine: ${file(config/step-functions/CW/netsuite-customer-ar-cw-state-machine.yml):stateMachine}
    netsuite-vendor-ap-cw-state-machine: ${file(config/step-functions/CW/netsuite-vendor-ap-cw-state-machine.yml):stateMachine}

    netsuite-ar-cw-restlet-state-machine: ${file(config/step-functions/CW_RESTLET_API/netsuite-ar-cw-state-machine.yml):stateMachine}
    netsuite-ap-cw-restlet-state-machine: ${file(config/step-functions/CW_RESTLET_API/netsuite-ap-cw-state-machine.yml):stateMachine}
    netsuite-customer-ar-cw-restlet-state-machine: ${file(config/step-functions/CW_RESTLET_API/netsuite-customer-ar-cw-state-machine.yml):stateMachine}
    netsuite-vendor-ap-cw-restlet-state-machine: ${file(config/step-functions/CW_RESTLET_API/netsuite-vendor-ap-cw-state-machine.yml):stateMachine}

    netsuite-ar-m1-state-machine: ${file(config/step-functions/M1/netsuite-ar-m1-state-machine.yml):stateMachine}
    netsuite-ap-m1-state-machine: ${file(config/step-functions/M1/netsuite-ap-m1-state-machine.yml):stateMachine}
    netsuite-customer-ar-m1-state-machine: ${file(config/step-functions/M1/netsuite-customer-ar-m1-state-machine.yml):stateMachine}
    netsuite-vendor-ap-m1-state-machine: ${file(config/step-functions/M1/netsuite-vendor-ap-m1-state-machine.yml):stateMachine}

    netsuite-ar-tr-state-machine: ${file(config/step-functions/TR/netsuite-ar-tr-state-machine.yml):stateMachine}
    netsuite-ap-tr-state-machine: ${file(config/step-functions/TR/netsuite-ap-tr-state-machine.yml):stateMachine}
    netsuite-customer-ar-tr-state-machine: ${file(config/step-functions/TR/netsuite-customer-ar-tr-state-machine.yml):stateMachine}
    netsuite-vendor-ap-tr-state-machine: ${file(config/step-functions/TR/netsuite-vendor-ap-tr-state-machine.yml):stateMachine}

    netsuite-ar-mcl-state-machine: ${file(config/step-functions/MC-LEOD/netsuite-ar-mcl-state-machine.yml):stateMachine}
    netsuite-customer-ar-mcl-state-machine: ${file(config/step-functions/MC-LEOD/netsuite-customer-ar-mcl-state-machine.yml):stateMachine}
    # netsuite-vendor-ap-mcl-state-machine: ${file(config/step-functions/MC-LEOD/netsuite-vendor-ap-mcl-state-machine.yml):stateMachine}
    # netsuite-ap-mcl-state-machine: ${file(config/step-functions/MC-LEOD/netsuite-ap-mcl-state-machine.yml):stateMachine}

    netsuite-intercompany-state-machine: ${file(config/step-functions/netsuite-intercompany-state-machine.yml):stateMachine}
    netsuite-tr-intercompany-state-machine: ${file(config/step-functions/netsuite-tr-intercompany-state-machine.yml):stateMachine}

    intera-company-wt-mcl-state-machine: ${file(config/step-functions/INTRA-COMPANY/intera-company-wt-mcl-state-machine.yml):stateMachine}
