---
function:
  handler: src/MC-LEOD/netsuite_ar_mcl.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ar-mcl-${self:provider.stage}
  description: MC-LEOD Netsuite  AR api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  environment:
    NETSUIT_RESTLET_INV_URL: ${ssm:/omni-dw/${self:provider.stage}/invoice/apiEndpointSb2}
    NETSUIT_RESTLET_CM_URL: ${ssm:/omni-dw/${self:provider.stage}/creditmemo/apiEndpointSb2}
    DATABASE_NAME: ${ssm:/omni-dw/${self:provider.stage}/databaseName}
  package:
    include:
      - src/MC-LEOD/netsuite_ar_mcl.js
      - Helpers/**
