---
function:
  handler: src/MC-LEOD/netsuite_ap_mcl.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ap-mcl-${self:provider.stage}
  description: MCL Netsuite  AP api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  environment:
    NETSUIT_RESTLET_VB_URL: ${ssm:/omni-dw/${self:provider.stage}/vendorbill/apiEndpointSb2}
    NETSUIT_RESTLET_VC_URL: ${ssm:/omni-dw/${self:provider.stage}/vendorcredit/apiEndpointSb2}
    DATABASE_NAME: ${ssm:/omni-dw/${self:provider.stage}/databaseName}
  package:
    include:
      - src/MC-LEOD/netsuite_ap_mcl.js
      - Helpers/**
