---
function:
  handler: src/MC-LEOD/netsuite_ar_mcl.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ar-mcl-${self:provider.stage}
  description: MC-LEOD Netsuite AR api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/MC-LEOD/netsuite_ar_mcl.js
      - Helpers/**
