---
function:
  handler: src/M1/netsuite_ar_m1.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ar-m1-${self:provider.stage}
  description: M1 Netsuite AR api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/M1/netsuite_ar_m1.js
      - Helpers/**
