---
function:
  handler: src/M1/netsuite_ar_m1.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ar-m1-${self:provider.stage}
  description: M1 Netsuite AR api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/M1/netsuite_ar_m1.js
      - Helpers/**
  environment:
    NETSUITE_VENDOR_M1_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-netsuite-vendor-ap-m1-state-machine-${self:provider.stage}
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
  	REGION: ${self:provider.region}