---
stateMachine:
  name: ${self:service}-netsuite-customer-ar-mcl-state-machine-${self:provider.stage}
  events:
    - schedule:
        rate: cron(30 10 * * ? *) #  UTC:- 9:300 AM / 4:00 am IST
  definition:
    Comment: "State machine to update netsuit customer AR mcl internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-netsuite-customer-ar-mcl-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      SuccessState:
        Type: Succeed
