---
stateMachine:
  name: netsuite-customer-ar-wt-restlet-${self:provider.stage}
  events:
    - schedule: 
        rate: cron(30 9 * * ? *) #  UTC:- 9:300 AM / 3:00 pm CST
  definition:
    Comment: "State machine to update netsuit customer AR WT restlet internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-netsuite-customer-ar-wt-restlet-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      SuccessState:
        Type: Succeed
