---
function:
  handler: src/mckesson_shipments_report.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-report-${self:provider.stage}
  description: Netsuite Report service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/mckesson_shipments_report.js
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    REGION: ${self:provider.region}
