---
function:
  handler: src/netsuite_currency.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-currency-${self:provider.stage}
  description: Netsuite Currency api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/netsuite_currency.js
      - Helpers/**
