---
function:
  handler: src/netsuite_intercompany_step_trigger.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-intercompany-step-trigger-${self:provider.stage}
  description: Netsuite intercompany step trigger function - ${self:provider.stage}
  runtime: nodejs14.x
  # events:
  #   - schedule:
  #       rate: cron(0 14 * * ? *) # UTC:- 2:00 PM
  #   - schedule:
  #       rate: cron(0 20 * * ? *) #  UTC:- 8:00 PM
  package:
    include:
      - src/netsuite_intercompany_step_trigger.js
  environment:
    NETSUITE_INTERCOMPANY_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-netsuite-intercompany-state-machine-${self:provider.stage}
