---
function:
  handler: src/wd_api.handler
  layers:
    - { Ref: CommonWmsLibsLambdaLayer }
  name: ${self:service}-wd-${self:provider.stage}
  description: WD api service - ${self:provider.stage}
  runtime: nodejs14.x
  timeout: 500

  package:
    include:
      - src/wd_api.js
      - Helpers/**
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    DBNAME: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    USER: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    HOST: ${ssm:/omni-dw/${self:provider.stage}/db/host~true}
    PASS: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    PORT: ${ssm:/omni-dw/${self:provider.stage}/db/port}
    WD_API: ${ssm:/omni-dw/${self:provider.stage}/api/wd}
    WD_API_USERNAME: ${ssm:/omni-dw/${self:provider.stage}/api/wd/username}
    WD_API_PASSWORD: ${ssm:/omni-dw/${self:provider.stage}/api/wd/password}
    WD_SHIPMENT_STATUS_TABLE: ${ssm:/omni-dw/${self:provider.stage}/wdShipmentStatus/table}
    WD_PDF_BOL_API_URL: ${ssm:/omni-dw/${self:provider.stage}/wdPdfBolApiUrl}
    WD_PDF_POD_API_URL: ${ssm:/omni-dw/${self:provider.stage}/wdPdfPodApiUrl}
    WD_PDF_API_KEY: ${ssm:/omni-dw/${self:provider.stage}/wdPdfApiKey}

  # events:
  #   - schedule: rate(30 minutes)
