---
stateMachine:
  name: ${self:service}-netsuite-intercompany-state-machine-${self:provider.stage}
  # events:
  #   - schedule:
  #       rate: cron(0 14 * * ? *) # UTC:- 2:00 PM
  #   - schedule:
  #       rate: cron(0 20 * * ? *) #  UTC:- 8:00 PM
  definition:
    Comment: "State machine to update netsuite intercompany invoices"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-netsuite-intercompany-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      SuccessState:
        Type: Succeed
