---
function:
  handler: src/WT_REST_API/netsuite_ar_wt.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ar-wt-restlet-${self:provider.stage}
  description: WT Netsuite AR  restlet api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  environment:
    NETSUIT_RESTLET_INV_URL: ${ssm:/omni-dw/${self:provider.stage}/invoice/apiEndpointSb2}
    NETSUIT_RESTLET_CM_URL: ${ssm:/omni-dw/${self:provider.stage}/creditmemo/apiEndpointSb2}
    DATABASE_NAME: ${ssm:/omni-dw/${self:provider.stage}/databaseName}
  package:
    include:
      - src/WT_REST_API/netsuite_ar_wt.js
      - Helpers/**
