---
function:
  handler: src/WT_REST_API/netsuite_ap_wt.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ap-wt-restlet-${self:provider.stage}
  description: WT Netsuite AP  restlet api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  environment:
    NETSUIT_RESTLET_VB_URL: ${ssm:/omni-dw/${self:provider.stage}/vendorbill/apiEndpoint}
    NETSUIT_RESTLET_VC_URL: ${ssm:/omni-dw/${self:provider.stage}/vendorcredit/apiEndpoint}
    DATABASE_NAME: ${ssm:/omni-dw/${self:provider.stage}/databaseName}
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    REGION: ${self:provider.region}
  package:
    include:
      - src/WT_REST_API/netsuite_ap_wt.js
      - Helpers/**
