---
function:
  handler: src/TR/netsuite_ar_tr.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ar-tr-${self:provider.stage}
  description: TR Netsuite AR api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  tags:
    Name: ar-tr
  package:
    include:
      - src/TR/netsuite_ar_tr.js
      - Helpers/**
  environment:
    NETSUITE_TR_VENDOR_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-netsuite-vendor-ap-tr-state-machine-${self:provider.stage}
