---
function:
  handler: src/TR/netsuite_ap_tr.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-netsuite-ap-tr-${self:provider.stage}
  description: TR Netsuite AP api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  tags:
    Name: ap-tr
  package:
    include:
      - src/TR/netsuite_ap_tr.js
      - Helpers/**
  environment:
    NETSUITE_TR_INTERCOMPANY_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-netsuite-tr-intercompany-state-machine-${self:provider.stage}
