---
function:
  handler: src/CW_RESTLET_API/netsuite_customer_ar_cw.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: ${self:service}-customer-ar-cw-restlet-${self:provider.stage}
  description: CW Restlet Netsuite customer AR api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  package:
    include:
      - src/CW_RESTLET_API/netsuite_customer_ar_cw.js
      - Helpers/**
  environment:
    # NETSUITE_AR_CW_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-netsuite-ar-cw-state-machine-${self:provider.stage}
    # NETSUITE_AR_CW_CUSTOMER_STEP_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-netsuite-customer-ar-cw-state-machine-${self:provider.stage}
