---
stateMachine:
  name: ${self:service}-netsuite-customer-ar-cw-state-machine-${self:provider.stage}
  events:
    - schedule:
        rate: cron(0 5 * * ? *) #  UTC:- 5:00 am
    - schedule:
        rate: cron(0 17 * * ? *) # UTC:- 8:00 pm
    - schedule:
        rate: cron(0 20 * * ? *) #  UTC:- 5:00 pm
  definition:
    Comment: "State machine to update netsuit customer AR cw internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-netsuite-customer-ar-cw-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      SuccessState:
        Type: Succeed
