---
stateMachine:
  name: ${self:service}-netsuite-customer-ar-cw-state-machine-${self:provider.stage}
  events:
    - schedule:
        rate: cron(0 15 * * ? *) # CST:- 10:00 AM GMT:- 3:00 pm
    - schedule:
        rate: cron(0 18 * * ? *) # CST:- 01:00 PM GMT:- 6:00 pm
    - schedule:
        rate: cron(0 20 * * ? *) # CST:- 03:00 PM GMT:- 8:00 pm
  definition:
    Comment: "State machine to update netsuit customer AR cw internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-netsuite-customer-ar-cw-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      SuccessState:
        Type: Succeed
