---
function:
  handler: src/PAID-INVOICES/paid_invoices.handler
  layers:
    - { Ref: CommonNetsuiteLibsLambdaLayer }
  name: netsuite-paid-invoices-${self:provider.stage}
  description: Netsuite paid  invoices api service - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  events:
    - schedule: 
        rate: cron(30 9 * * ? *) #  UTC:- 9:30 AM / 3:00 pm IST
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    REGION: ${self:provider.region}
  package:
    include:
      - src/PAID-INVOICES/paid_invoices.js
      - Helpers/**
